SurPathHub/SurPathHub.github.io

index.html

changed social media icons

---

assets/css/styles.css

Fixed the footer style

---

assets/css/styles.css
index.html

feat: Redesign Homepage - changed text and embeded youtube

---

assets/css/styles.css
index.html

Add button for discrd and github accounts, Add hover effect

---

assets/css/styles.css
index.html

Hey, I have designed the join us section and it is responsive.

desinged join us section

---

assets/css/styles.css

I fix the bx bx-menu & bx bx-x bug issue by changing the media query of min-width: 1024 into 769.

bx bx-menu & bx bx-x fixed

---

assets/js/main.js

- nav__menu is not closing when nav__links was clicked
Closes: #77
Add close menu function when nav__links was clicked

Add close menu function when nav__links was clicked

---

assets/css/styles.css
index.html

- Info about the related issue 
Closes: #86 
Give a clear description what modifications you have made
In the footer section of 'Index.html', added a new <p> class ="footer__credits" with text "Powered by" followed by logos of github and Dev protocol<img> with class = "git__link".
In style.css, accessed the class "footer_credits" and set the display to inline-flex, and justify content: center and margin of 30px.
- [] Code style update (formatting, local variables)
- [] This change requires a documentation update
Describe how have you verified the changes made
- [] I have commented my code, particularly whereever it was hard to understand.
- [] I have made corresponding changes to the documentation.
- [] I have added tests that prove my fix is effective …

Powered by footer

---

index.html

- Added more members in the members section
Closes: #85 
Added 3 more members to the members page
Describe how have you verified the changes made
original screenshot | ![Screenshot 2021-08-22 151543](https://user-images.githubusercontent.com/53107832/130352789-c5381a44-49c2-4115-973b-6b6f6a39f62d.png) |

added members

---

index.html

docs: changed Ryjin210's role

---

index.html

closes #99
Corrected Dayong's link in the project highlights section of SurPath Hub's site.
Link should go to the correct page.
N/A | N/A |

refactor: update project links

---

index.html

- Improve SEO.
This has been tested and resources were taken from https://ahrefs.com/blog/open-graph-meta-tags/. All working well.

feat: Improve SEO

---

assets/css/styles.css

- The issue only comes when we try to open the page on Firefox and the issue is still there. May be in Firefox there is some issue with the rendering engine but there is a fix for this.
Closes: #110, #84  
Changed the `style.css` file 
```  diff
.container-join{
....
....
+ postion:inherit
}
```
Try to open the page in the Firefox web browser

fix:110;84

---

assets/css/styles.css
index.html

#116
Closes: #116 
I have added a blog section in the index.html and linked that section with the navbar. I have updated the styles.css in order to implement the styling of the blog section.
I have run the index.html file in chrome browser and the website is perfectly rendering all the content.
| ![image](https://user-images.githubusercontent.com/64556550/194725611-43a9fb4b-9d6f-4354-b275-03fcceae92f8.png) |

FEAT: added the blogs section

---

assets/css/styles.css
index.html

Support Our Program section added

---

index.html

Closes: #122
Join Us section removed because it is necessary for rebranding

old join section and nav link removed

---

assets/css/styles.css
img/acce_career_icon.svg
img/access_event_icon.svg
img/grow_network_icon.svg
img/intership_icon.svg
img/mentorship_icon.svg
img/swag_rewards_icon.svg
index.html

Closes: #114 
added the section 'Why be part of SurPath Hub'

🔥Created the section 'Why be part of SurPath Hub' #114

---

.github/workflows/deploy_node.yaml
package-lock.json
yarn.lock

Closes: #133  
Added a node deploy workflow for the new website.

[feat]: add nextjs github page build workflow

---

next.config.js

fix: 🔧 update the next.config file to be able to run the workflow

---

.github/ISSUE_TEMPLATE/bug_report.yml

Fix: fixed the bug template, using correct title and textarea for content

---

README.md

Docs: Add "Getting Started" to run the project

---

src/components/homepage/JoinCommunity.js

Update the Join our Community section
